### PR TITLE
check for tests before launching GUI

### PR DESCRIPTION
**Pull request by restonslacker**
addresses #1 

runs the same `devtools` check but happens before gui is run.

if no tests are found, the GUI will not run but the user is given the option to create tests.

### CODE REVIEW

**Review by krlmlr — COMMENTED** [review]
Thanks. Maybe just run the first `devtools::test()` in `shine()` (via `get_run_output()`) and initialize `run_output` before starting the GUI? Need to be careful to avoid running twice during initialization.

**Comment by restonslacker** [comment]
Let me think a little about it.  If there are no tests at all, even if a user tells `devtools` to setup the test framework, there are still no tests so we shouldn't run the GUI.

**Comment by krlmlr** [comment]
Running the GUI is not necessarily an error, the user can start writing tests while the GUI is running.

I don't like the lockdown of the shell, which prevents the user to ask `devtools::use_test()`. But then we could also create a button "New test" in our GUI.

**Comment by restonslacker** [comment]
That's a fair perspective WRT treating the lack of tests ad an error or locking the user out of the GUI. So the key is to check for the presence of tests before calling `devtools::test()` because if they don't exist, devtools will print the same message on the console. 

It's been a while since I've really used shiny but IIRC, we could use a conditoinal panel that would display the basic question and install/cancel buttons if there are no tests. If the test framework is present, even with zero tests, we display the current GUI instead. 

does this seem like a reasonable plan?

**Comment by krlmlr** [comment]
Yes, why not. But that seems like a lot of effort for relatively little gain. It would be simpler just to do the first `devtools::test()` run in `shine()`. The following issues seem to be important as well:

- A visual indication that the tests are running (by greying out the app, or the radio buttons, or...)
- Running without blocking the console (might be possible with some adaptation to testthat)
- A better layout
- Re-running only failed tests
- A daemon that is running in the background and responsible for providing test results
    - Run on file save
    - Remember test runs after closing and re-opening the app
- Saving and restoring the selection when re-running tests
- A better control for displaying test results and stack traces

And this is just my personal wish list ;-)

**Pull request closed without merging**
